version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: "ecommerce_project"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    links:
      - db

# sudo docker-compose up -d run elemek ucun
# sudo docker ps -a   aktiv olub olmamagina baxmag
# sudo docker-compose down  aktiv olan containerleri dayandirmag