# Generated by Django 3.1 on 2020-09-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200913_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyvalue',
            options={'ordering': ('order', '-created_at'), 'verbose_name': 'Property Value', 'verbose_name_plural': 'Property Values'},
        ),
        migrations.AlterField(
            model_name='propertyname',
            name='category',
            field=models.ManyToManyField(related_name='property_names', to='core.Category', verbose_name='Category'),
        ),
    ]
