# Generated by Django 3.1 on 2020-09-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200913_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productproperties',
            options={'verbose_name': 'Product Properties', 'verbose_name_plural': 'Product Properties'},
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compaign', models.CharField(max_length=120, verbose_name='Compaign')),
                ('discount_type', models.BooleanField(choices=[('1', 'Faiz'), ('2', 'Manat')], verbose_name='Discount Type')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Discount Amount')),
                ('deadline', models.DateTimeField(verbose_name='Deadline')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(related_name='product_discounts', to='core.Product', verbose_name='Product Discounts')),
            ],
            options={
                'verbose_name': 'Product Discount',
                'verbose_name_plural': 'Product Discounties',
            },
        ),
    ]
