# Generated by Django 3.1 on 2020-10-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200923_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('image', models.ImageField(upload_to='bonuse')),
                ('description', models.TextField(verbose_name='Description')),
                ('bonuse', models.IntegerField(default=5, verbose_name='Bonuse')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bonuse',
                'verbose_name_plural': 'Bonuses',
                'ordering': ('created_at',),
            },
        ),
    ]
