# Generated by Django 3.1 on 2020-10-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bonuse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuse',
            name='image',
            field=models.FileField(upload_to='bonuse'),
        ),
    ]
