# Generated by Django 3.1.2 on 2020-10-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201009_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='discount_type',
            field=models.IntegerField(choices=[(1, 'Faiz'), (2, 'Manat')], verbose_name='Discount Type'),
        ),
    ]
