# Generated by Django 3.1 on 2020-09-13 10:32

import core.tools.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Man'), (2, 'Women')], null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[core.tools.validators.phone_number_validator], verbose_name='Phone number'),
        ),
    ]
