# Generated by Django 3.1.2 on 2020-10-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200913_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Cinsiyyətinizi seçin'), (1, 'Kişi'), (2, 'Qadın')], default=0, null=True, verbose_name='Gender'),
        ),
    ]
